# Generated by Django 4.2.1 on 2023-06-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrawing_app', '0002_comic_comment_comic_content_game_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic_comment',
            name='page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comic_content',
            name='page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dateselect',
            name='numpage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game_comment',
            name='page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game_content',
            name='page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news_comment',
            name='page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news_content',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
