# Generated by Django 4.2.1 on 2023-06-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrawing_app', '0004_alter_dateselect_numpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateselect',
            old_name='numpage',
            new_name='comicpage',
        ),
        migrations.AddField(
            model_name='dateselect',
            name='gamepage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dateselect',
            name='newspage',
            field=models.IntegerField(default=1),
        ),
    ]
