# Generated by Django 4.2.1 on 2023-06-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrawing_app', '0005_rename_numpage_dateselect_comicpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic_comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comic_content',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game_comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game_content',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news_content',
            name='content',
            field=models.TextField(),
        ),
    ]
