# Generated by Django 4.2.1 on 2023-06-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodrawing_app', '0006_alter_comic_comment_content_and_more'),
    ]

    operations = [
    ]
